### ISSUE TITLE
Replace main image with 3D hosted image.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#1]
Replace the main image (pictured) with the 3D hosted image using to code below.
![20220622123801](https://user-images.githubusercontent.com/37931/175121948-69a5ce19-12bd-4e0e-b9ff-4ebed538fc36.png)

3D image code
```
<iframe title="Nervos Durag" frameborder="0" allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share src="https://sketchfab.com/models/a511c8f760ba4b79b75e900f86af5211/embed"> </iframe>
```

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-28 17-34-41](https://user-images.githubusercontent.com/47236913/176174220-615f4895-ceb7-4b5b-8ad4-bb130e68b555.png)
![Screenshot from 2022-06-28 17-34-48](https://user-images.githubusercontent.com/47236913/176174228-1ea5a8ab-4c12-4ca3-930c-16dc40ca5829.png)

After adding iframe elements it looks like this, The image is looking good instead of this 3D model

let me know what should I do with this, I am not gonna push this changes

**Comment by jordanmack** [comment]
We can leave it using the current static image for now.
